package sk.watchaccuracy

/**
 * Searchable, offline catalog of model families, not a reference-number database.
 * It intentionally includes historic families and leaves both fields editable so
 * discontinued models, special editions and unlisted makers can still be recorded.
 */
internal object WatchCatalog {
    val models: Map<String, List<String>> = linkedMapOf(
        // Established manufacturers
        "A. Lange & Söhne" to listOf("Lange 1", "Saxonia", "1815", "Zeitwerk", "Odysseus", "Datograph"),
        "Alpina" to listOf("Alpiner", "Startimer", "Seastrong", "Heritage"),
        "Armin Strom" to listOf("Gravity Equal Force", "Mirrored Force Resonance", "Orbit", "One Week"),
        "Audemars Piguet" to listOf("Royal Oak", "Royal Oak Offshore", "Code 11.59"),
        "Baume & Mercier" to listOf("Riviera", "Clifton", "Classima", "Hampton"),
        "Bell & Ross" to listOf("BR 03", "BR 05", "BR-X5", "BR V2"),
        "Blancpain" to listOf("Fifty Fathoms", "Villeret", "Air Command", "Léman"),
        "Bovet" to listOf("Récital", "Fleurier", "Virtuoso"),
        "Breguet" to listOf("Classique", "Marine", "Tradition", "Type XX", "Reine de Naples"),
        "Breitling" to listOf("Navitimer", "Chronomat", "Superocean", "Superocean Steelfish", "Avenger", "Premier", "Top Time", "Endurance Pro"),
        "Bremont" to listOf("Supermarine", "Terra Nova", "Altitude", "Martin-Baker"),
        "Bulova" to listOf("Lunar Pilot", "Accutron", "Marine Star", "Precisionist", "Jet Star"),
        "Cartier" to listOf("Tank", "Santos", "Ballon Bleu", "Panthère", "Pasha"),
        "Casio" to listOf("G-SHOCK", "Edifice", "Pro Trek", "Oceanus", "F-91W", "A168"),
        "Certina" to listOf("DS Action", "DS PH200M", "DS-1", "DS Podium", "DS-7"),
        "Citizen" to listOf("Promaster", "Tsuyosa", "Series 8", "The Citizen", "Attesa", "Eco-Drive One"),
        "Doxa" to listOf("SUB 200", "SUB 300", "SUB 300T", "SUB 600T", "SUB 1500T"),
        "Eberhard & Co." to listOf("Chrono 4", "Scafograf", "Traversetolo", "Extra-fort"),
        "Eterna" to listOf("KonTiki", "Super KonTiki", "Heritage", "Soleure"),
        "F.P. Journe" to listOf("Chronomètre Bleu", "Chronomètre Souverain", "Octa", "Élégante"),
        "Fortis" to listOf("Flieger", "Marinemaster", "Stratoliner", "Novonaut"),
        "Franck Muller" to listOf("Vanguard", "Cintrée Curvex", "Crazy Hours", "Long Island"),
        "Frederique Constant" to listOf("Highlife", "Classics", "Manufacture", "Slimline"),
        "Girard-Perregaux" to listOf("Laureato", "Bridges", "1966", "Vintage 1945"),
        "Glashütte Original" to listOf("SeaQ", "PanoMaticLunar", "Senator", "Sixties", "Seventies"),
        "Grand Seiko" to listOf("Heritage", "Elegance", "Sport", "Evolution 9", "Spring Drive", "Tentagraph"),
        "Hamilton" to listOf("Khaki Field", "Khaki Aviation", "Khaki Navy", "Jazzmaster", "Ventura", "American Classic"),
        "Hanhart" to listOf("417 ES", "Pioneer", "Preventor", "Primus"),
        "Hublot" to listOf("Big Bang", "Classic Fusion", "Spirit of Big Bang", "Square Bang"),
        "IWC" to listOf("Pilot's Watch", "Portugieser", "Portofino", "Ingenieur", "Aquatimer", "Da Vinci"),
        "Jaeger-LeCoultre" to listOf("Reverso", "Master Control", "Master Ultra Thin", "Polaris", "Rendez-Vous", "Duomètre"),
        "Junghans" to listOf("max bill", "Meister", "FORM", "1972"),
        "Longines" to listOf("Spirit", "HydroConquest", "Legend Diver", "Master Collection", "Conquest", "DolceVita", "Heritage"),
        "Maurice Lacroix" to listOf("AIKON", "Pontos", "Masterpiece", "Fiaba"),
        "Mido" to listOf("Ocean Star", "Multifort", "Commander", "Baroncelli"),
        "Montblanc" to listOf("1858", "Star Legacy", "Heritage", "Tradition"),
        "Nomos Glashütte" to listOf("Tangente", "Club", "Orion", "Metro", "Ahoi", "Autobahn", "Tetra"),
        "Omega" to listOf("Speedmaster", "Seamaster 300", "Seamaster Diver 300M", "Seamaster Aqua Terra", "Planet Ocean", "Constellation", "De Ville"),
        "Oris" to listOf("Aquis", "Divers Sixty-Five", "Big Crown Pointer Date", "ProPilot", "Artelier"),
        "Panerai" to listOf("Luminor", "Radiomir", "Submersible", "Luminor Due"),
        "Patek Philippe" to listOf("Calatrava", "Nautilus", "Aquanaut", "Complications", "Grand Complications", "Cubitus"),
        "Parmigiani Fleurier" to listOf("Tonda PF", "Toric", "Kalpa"),
        "Piaget" to listOf("Polo", "Altiplano", "Limelight Gala"),
        "Rado" to listOf("Captain Cook", "True Square", "Centrix", "DiaStar", "Ceramica"),
        "Raymond Weil" to listOf("Freelancer", "Maestro", "Toccata", "Millesime"),
        "Rolex" to listOf("Oyster Perpetual", "Oyster Perpetual 41", "Datejust", "Day-Date", "Submariner", "GMT-Master II", "Explorer", "Explorer II", "Cosmograph Daytona", "Sea-Dweller", "Yacht-Master", "Sky-Dweller"),
        "Seiko" to listOf("Seiko 5 Sports", "Prospex", "Prospex Save the Ocean", "Presage", "Astron", "King Seiko", "Alpinist"),
        "Sinn" to listOf("104", "556", "356", "903", "U1", "U50", "EZM", "Frankfurt Financial District"),
        "Squale" to listOf("1521", "Super-Squale", "Sub-39", "Matic"),
        "Stowa" to listOf("Flieger", "Flieger A", "Flieger B", "Marine", "Antea", "Seatime"),
        "Swatch" to listOf("Originals", "Sistem51", "Irony", "Bioceramic MoonSwatch", "Bioceramic Scuba Fifty Fathoms"),
        "TAG Heuer" to listOf("Carrera", "Monaco", "Aquaracer", "Formula 1", "Autavia", "Link"),
        "Tissot" to listOf("PRX", "PRS 516", "Le Locle", "Gentleman", "Seastar", "T-Touch", "Heritage"),
        "Tudor" to listOf("Black Bay", "Black Bay 41", "Black Bay 58", "Black Bay GMT", "Pelagos", "Ranger", "Royal", "1926", "Heritage Chrono"),
        "Ulysse Nardin" to listOf("Diver", "Maxi Marine Diver", "Marine", "Freak", "Blast"),
        "Vacheron Constantin" to listOf("Overseas", "Patrimony", "Traditionnelle", "Fiftysix", "Historiques"),
        "Zenith" to listOf("Chronomaster", "Defy", "Pilot", "Elite"),
        // Independent makers and microbrands (including historical collections)
        "Alexander Shorokhoff" to listOf("Avantgarde", "Regulator", "Kandy", "Winter", "Crossing", "Shar"),
        "anOrdain" to listOf("Model 1", "Model 2", "Model 3"),
        "Archimede" to listOf("Pilot", "Outdoor", "1950", "Klassik"),
        "Baltic" to listOf("Aquascaphe", "MR01", "HMS", "Bicompax", "Hermétique", "Prismic"),
        "Biatec" to listOf("Corsair", "Majestic", "Leviathan", "Marine", "Heritage", "Fusion", "Magnifique"),
        "Boldr" to listOf("Venture", "Odyssey", "Expedition", "Field Medic"),
        "Brew Watch Co." to listOf("Metric", "Retrograph", "Super Metric", "Brew 8-Bit"),
        "Christopher Ward" to listOf("C60 Trident", "C63 Sealander", "C65 Aquitaine", "The Twelve", "C1 Bel Canto", "C1 Moonphase"),
        "Circula" to listOf("AquaSport", "SuperSport", "ProTrail", "Heritage"),
        "Damasko" to listOf("DA44", "DA36", "DS30", "DK30", "DK32", "DC56", "DSub"),
        "Dan Henry" to listOf("1937", "1939", "1945", "1962", "1964", "1970", "1972", "1975"),
        "Dornblüth & Sohn" to listOf("99.0", "99.1", "99.2", "Quintus"),
        "DWISS" to listOf("Emme", "M1", "M2", "M3", "M3W", "M3S", "R1", "R2"),
        "Farer" to listOf("Lander", "Resolute", "Mansfield", "Aquamatic", "Endeavour", "Moonphase"),
        "Formex" to listOf("Essence", "Reef", "Field", "Space Rock"),
        "Furlan Marri" to listOf("Mechaquartz", "Havana Salmon", "Sector", "Disco Volante"),
        "Guinand" to listOf("Series 40", "Series 41", "Series 60", "Series 90"),
        "Halios" to listOf("Seaforth", "Universa", "Fairwind", "Puck"),
        "Horage" to listOf("Autark", "Supersede", "Lensman", "Tourbillon 1"),
        "Kudoke" to listOf("Kudoke 1", "Kudoke 2", "Kudoke 3"),
        "Kurono Tokyo" to listOf("Chronograph", "Calendrier", "Toki", "Reiwa"),
        "Laco" to listOf("Pilot", "Original Pilot", "Aachen", "Augsburg", "Münster", "Leipzig", "Scorpion"),
        "Laventure" to listOf("Marine", "Sous-Marine", "Transatlantique GMT", "Automobile"),
        "Lorier" to listOf("Neptune", "Falcon", "Hyperion", "Gemini", "Astra"),
        "Maen" to listOf("Manhattan", "Hudson", "Skymaster", "Brooklyn"),
        "Ming" to listOf("17.09", "37.05", "37.07", "20.01", "27.01"),
        "Monta" to listOf("Oceanking", "Noble", "Skyquest", "Atlas", "Triumph"),
        "Nodus" to listOf("Sector", "Contrail", "Duality", "Retrospect"),
        "Oak & Oscar" to listOf("Olmsted", "Humboldt", "Jackson", "Atwood"),
        "Orion Watches" to listOf("Hellcat", "Sylph", "Calamity"),
        "Phoibos" to listOf("Eagle Ray", "Wave Master", "Leviathan", "Proteus"),
        "Prim" to listOf("Sport", "Sport 1", "Orlík", "Diplomat", "Pavouk", "Spartak"),
        "Raven Watches" to listOf("Trekker", "Endeavour", "Solitude", "Airfield"),
        "RZE" to listOf("Endeavour", "Resolute", "Ascentus", "Fortitude"),
        "Serica" to listOf("4512", "5303", "8315", "6190"),
        "Smiths" to listOf("Everest", "PRs-25", "Commander", "Caribbean"),
        "Steinhart" to listOf("Ocean One", "Ocean 39", "Nav B-Uhr", "Ocean Vintage", "Apollon"),
        "Studio Underd0g" to listOf("Series 01", "Series 02"),
        "Traska" to listOf("Commuter", "Summiteer", "Freediver", "Seafarer", "Venturer"),
        "Unimatic" to listOf("Modello Uno", "Modello Due", "Modello Tre", "Modello Quattro"),
        "Venezianico" to listOf("Nereide", "Nereide GMT", "Nereide Ultraleggero", "Redentore", "Arsenale", "Bucintoro"),
        "Vero" to listOf("Open Water", "Meridian", "Workhorse"),
        "Yema" to listOf("Superman", "Rallygraf", "Navygraf", "Urban Traveller", "Wristmaster"),
        "Zelos" to listOf("Swordfish", "Mako", "Hammerhead", "Spearfish", "Horizons", "Skyraider")
    )

    val brands: List<String> = models.keys.sortedWith(String.CASE_INSENSITIVE_ORDER)

    fun modelsFor(brand: String): List<String> =
        models.entries.firstOrNull { it.key.equals(brand.trim(), ignoreCase = true) }?.value.orEmpty()
}
